version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      #- echo Installing Jest...
      #- npm install -g jest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      
      # Install dependencies needed for running tests
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      #- echo Testing with Jest
      #- npm run test
  post_build:
    commands:
      # Remove existing node_modules to clear dev dependencies
      - rm -r node_modules

      # Install runtime dependencies
      - npm install --production
artifacts:
  type: zip
  files:
    - dist/*
    - docs/*