version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    #  - echo Installing Jest...
    #  - npm install -g jest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
    #  - echo Testing with Jest
    #  - npm run test
  post_build:
    commands:
      - rm -r node_modules
      - npm install --production
artifacts:
  type: zip
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json